<?php

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 */
function corporative_site_install() {
  include_once DRUPAL_ROOT . '/profiles/standard/standard.install';
  standard_install();
  
  // Enable transliteration on paths (á turns into a)
  variable_set('pathauto_transliterate', 1);

  // Create an empty page as the front page
  $fields = array('path' => 'home');
  db_insert('empty_page')->fields($fields)->execute();
  variable_set('site_frontpage', 'home');

  // Place the search box in the header region
  db_update('block')->fields(
    array(
      'region' => 'header',
    )
  )
  ->condition('module', 'search', '=')
  ->condition('theme', 'bartik', '=')
  ->execute();

  // Allow file uploads with CKeditor for Full HTML input filter
  $result = db_select('ckeditor_settings', 's')
    ->fields('s')
    ->condition('name', 'Full', '=')
    ->execute()
    ->fetchAssoc();
  $result['settings'] = unserialize($result['settings']);
  $result['settings']['filebrowser'] = 'imce';
  db_update('ckeditor_settings')->fields(
    array(
      'settings' => serialize($result['settings']),
    )
  )
  ->condition('name', 'Full', '=')
  ->execute();
}
